### PR TITLE
LPS-85960 Added flag to bypass URL modification for absolute URLs

### PR DESCRIPTION
**Pull request by ricky-pan**
@ [LPS-85960](https://issues.liferay.com/browse/LPS-85960)
Issue: When staging, Liferay parses URLs in content to check for relative URLs within different environments and modifies them as needed to preserve links. It does this for both relative and absolute URLs. In this case, an absolute URL does not follow Liferay's URL formats and is modified, thus breaking the link upon staging.

Solution: I added a flag that tests to see whether the URL is an absolute or relative URL. If it is determined that a URL is absolute, it will not make any changes to the address, thus preserving the link.

### CODE REVIEW

**Comment by ricky-pan** [comment]
ci:test:relevant

**Comment by joshuacords** [comment]
ci:test:relevant

**Comment by joshuacords** [comment]
Reviewing now.

**Comment by joshuacords** [comment]
Hello @ricky-pan,
Thanks for looking into the tests, sorry it took me a while to get to this.

I've tested this and it does not fix the issue. It looks like you're saving the url after the '/' has already been removed from the end. Also you have the relativeURLFlag initialized outside of the while loop which would create problems the second time through. I recommend testing with multiple relative and absolute href anchors in the same content.

Also, "relativeURL" or "absoluteURL" is more uniform across Liferay than "relativeURLFlag".

**Pull request closed without merging**
