### PR TITLE
Do not transform sql when reindexing because we need to return all re…

### PR DESCRIPTION
**Pull request by noornajj**
Steps to reproduce:

1. Enable publications
2. Create two publications P1 and P2
3. In each publication create a web content (test1 and test2 respectively)
4. Run a search reindex for Journal Article while checked out to P1
5. For each publication: Go to Content -> Web Content and search for test
**Expected behavior:** Both publications should show their respective web content in the search results
**Actual behavior:** Only P1's web content is searchable
6. Run a full search reindex  while checked out to P1
7. Repeat step 5
**Expected behavior:** Both publications should show their respective web content in the search results
**Actual behavior:** Neither publication's web content is searchable

I used web content in the steps but this applies to any asset

### CODE REVIEW

**Comment by joshuacords** [comment]
Hi @noornajj,
I think this approach is fine, but you should do it much higher up in the logic and for both the general company full reindexes and the specific class reindexes. Here's the 2 locations I would use:

- [Full Reindex](https://github.com/liferay/liferay-portal/blob/b93d0af2c7e3389e70864452c7ca47fdd2c089be/modules/apps/portal-search/portal-search/src/main/java/com/liferay/portal/search/internal/background/task/ReindexPortalBackgroundTaskExecutor.java#L65)
- [Model Reindex](https://github.com/liferay/liferay-portal/blob/e5f8b328f641055e801c5e2d747190d3725b6572/modules/apps/portal-search/portal-search/src/main/java/com/liferay/portal/search/internal/background/task/ReindexSingleIndexerBackgroundTaskExecutor.java#L134)

Let me know if you have more questions.

**Comment by noornajj** [comment]
Hi @joshuacords 

Thank you for your help on this. I was able to get this to work for the model reindex but not for the full reindex.
For the full reindex, the value of CTCollectionThreadLocal gets updated sometime after setting it [here](https://github.com/liferay/liferay-portal/blob/b93d0af2c7e3389e70864452c7ca47fdd2c089be/modules/apps/portal-search/portal-search/src/main/java/com/liferay/portal/search/internal/background/task/ReindexPortalBackgroundTaskExecutor.java#L65)

The reason is due to this [thread pool](https://github.com/liferay/liferay-portal/blob/e5f8b328f641055e801c5e2d747190d3725b6572/modules/apps/portal-search/portal-search/src/main/java/com/liferay/portal/search/internal/SearchEngineInitializer.java#L150-L171) 
I tried setting the value inside this call method but that didn't work either. The CTCollectionThreadLocal value gets removed [here](https://github.com/liferay/liferay-portal/blob/e5f8b328f641055e801c5e2d747190d3725b6572/modules/apps/portal-search/portal-search/src/main/java/com/liferay/portal/search/internal/indexer/IndexerWriterImpl.java#L176) inside setCompanyId.

When executing through a thread pool, CompanyThreadLocal is initially 0 and being set a valid id which leads _setCompanyId to return true and therefore removes CTCollectionThreadLocal. https://github.com/liferay/liferay-portal/blob/e5f8b328f641055e801c5e2d747190d3725b6572/portal-kernel/src/com/liferay/portal/kernel/security/auth/CompanyThreadLocal.java#L76-L78

What should I do in this case? Should I make the changes inside of IndexerWriter as I initially had?

**Comment by joshuacords** [comment]
Hi @noornajj, given what you've described, making the changes inside the IndexerWriter like you did on this PR to handle the full reindex, and making changes for the Model Reindex as described above seems like a fine solution.

**Comment by noornajj** [comment]
Thank you @joshuacords

**Pull request closed without merging**
