### PR TITLE
LPS-84785 LPS-111601

### PR DESCRIPTION
**Pull request by joshuacords**
https://issues.liferay.com/browse/LPS-84785
https://issues.liferay.com/browse/LPS-111601

Changes for DLFolders yet to come.

### CODE REVIEW

**Comment by joshuacords** [comment]
ci:test:sf

**Comment by joshuacords** [comment]
ci:test:sf:norebase

**Comment by lipusz** [comment]
Hey Josh,

Did you talk to André regarding to cross-check the changes with the Lima (Collaboration) and WEM teams too when you will be sending to master?

**Comment by joshuacords** [comment]
Hi @lipusz,

I'm not used to these types of approvals. The code change in the other services only affects search indexing, but if it's important to get confirmation I will. This PR is just the first stage which I was going to have Adam review. I still need to add changes for DLFolders but we figured it's better to get some review in before copying code to the folders.

**Comment by joshuacords** [comment]
ci:test:sf:norebase

**Comment by joshuacords** [comment]
ci:test:sf:norebase

**Comment by joshuacords** [comment]
ci:test:sf:norebase

**Comment by joshuacords** [comment]
ci:test:sf:norebase

**Comment by joshuacords** [comment]
ci:test:search:norebase

**Pull request closed without merging**
