### PR TITLE
LPS-86181 Obscure sensitive User information in logs

### PR DESCRIPTION
**Pull request by ricky-pan**
@[LPS-86161](https://issues.liferay.com/browse/LPS-86161) [#34](https://github.com/joshuacords/liferay-portal/pull/34)
Issue: When Liferay encounters database-related exceptions regarding the User model, the entire model is stored into the logs, including the hashed password and the plaintext security question answer, as well as personal information such as name, birthday, and email. According to OWASP (Open Web Application Security Project), it is [good practice](https://www.owasp.org/index.php/Logging_Cheat_Sheet) to not ever log sensitive information, as is currently done in handling StaleObject exceptions.

Solution: In the case of a StaleObject exception, I added a check that the logging level must be set to Debug for the model to be recorded. Specifically for stale User objects, I also obscure fields that may contain personal information.

### CODE REVIEW

**Comment by ricky-pan** [comment]
ci:test:relevant

**Comment by joshuacords** [comment]
ci:retest

**Comment by joshuacords** [comment]
Reviewing :)

**Comment by joshuacords** [comment]
Forwarded here: https://github.com/SamZiemer/liferay-portal/pull/512

**Pull request closed without merging**
