### PR TITLE
LPS-84351 Removed infinite loop from onDataReady

### PR DESCRIPTION
**Pull request by ricky-pan**
Issue: @ [LPS-84351](https://issues.liferay.com/browse/LPS-84351)
Previous PR: [685](https://github.com/MichaelPrigge/liferay-portal-ee/pull/685)

This commit fixes an infinite loop within `_onDataReady`, which is fired again before the flag can be reset. The infinite loop is never accessed in master and 7.1.x, but produces a bug in 7.0.x, referenced in [LPS-84351](https://issues.liferay.com/browse/LPS-84351). The fix for the bug will be backported from this change in master. While it does not affect functionality in master or 7.1.x, fixing this function will prevent issues from this function from arising in the future.

### CODE REVIEW

**Comment by joshuacords** [comment]
ci:test:relevant

**Comment by joshuacords** [comment]
Hello @ricky-pan,
Typically when you send a new PR you will want to comment "ci:test:relevant" like I did above so that Continuous Integration tester will test your changes.

**Comment by joshuacords** [comment]
Hello @ricky-pan,

I understand that in 7.0.x [this if logic](https://github.com/joshuacords/liferay-portal/pull/25/commits/b8c1525e82faada39868063fdbc5719f8581afd5#diff-4f17afed4f4ae093ffefe64e0b49881bR321) is called, but this is not called in master. Can you explain why this isn't called in master and why that logic isn't applicable for 7.0.x?

**Comment by ricky-pan** [comment]
Hi @joshuacords,

The if logic that is being called in 7.0.x is aimed at saving values if a user wanted to switch localizations (and render the editor) before the editor was ready to render. In master, this situation is avoided by setting an additional check for customDataProcessors. Initializing the data in the editor was moved to this step, set to execute after the instance was ready, meaning that there would never be a value in pendingData, circumventing the loop. This logic in theory works in 7.0.x, but this file in master has changed since this commit, so backporting the entire solution through checking for customDataProcessor is less straightforward and possibly excessive when an infinite loop is causing the problem.

**Comment by joshuacords** [comment]
Forwarded here: https://github.com/SamZiemer/liferay-portal/pull/504

**Pull request closed without merging**
