### PR TITLE
LPS-85102

### PR DESCRIPTION
**Pull request by diana-lin**
LPS: https://issues.liferay.com/browse/LPS-85102

Problem: When creating a new blog, "Blog Entry URL" remains untranslated in the Japanese localization.  We expect to see "Blog Entry URL" in Japanese as "ブログエントリーのURL", but the English translation is shown instead.

Solution:  Update the language key to use the Japanese translation.

### CODE REVIEW

**Comment by diana-lin** [comment]
ci:test:relevant

**Comment by joshuacords** [comment]
Hello @diana-lin,

Unfortunately, even though this looks like the correct translation we don't do translation manually. Instead we need someone with the translation service to build languages.

I'll see where to go from here.

**Comment by diana-lin** [comment]
Okay, I see.  Alright, sounds good.

**Comment by joshuacords** [comment]
Well, after researching it further it seems we don't want to use buildLang with Japanese. And considering this was reported by Brian Suh, a CSE in Japan, with the expected translation, I'm going to trust his translation.

**Comment by joshuacords** [comment]
Forwarded here: https://github.com/SamZiemer/liferay-portal/pull/509

**Pull request closed without merging**
