### PR TITLE
LPS-112882 Apply permission filter to total results

### PR DESCRIPTION
**Pull request by SamZiemer**
/cc @amandaaakwok

Notes from Amanda:
> [LPS-112882](https://issues.liferay.com/browse/LPS-112882)
> 
> **Issue:** When pagination is set, the search results show an incorrect number of total entries for users who have limited view permissions
> 
> **Scenario:** Assume we have a total of 16 documents all with a description of "issue",  limit the permission of 2 of those documents to a specific role (role B), and perform a search of "issue" while logged in as a user without role B. 
> 
> If delta is set to 4 and we navigate to page 2, `hit` will hold documents 0-7, but the number of hits will remain 16. In https://github.com/amandaaakwok/liferay-portal/blob/f2ec395a77e3a26b19e1398c641984b22dd7b8e4/modules/apps/portal-search/portal-search/src/main/java/com/liferay/portal/search/internal/permission/DefaultSearchResultPermissionFilter.java#L134, the permission filter is applied only to documents 0-7 and not documents 8-15; the portal isn't configured to check to see if the user has permission to view the second range (8-15). This proves to be problematic when calculating the total for the search container, where the total number of results displayed (16) does not reflect the total number of results that the user has permission to see (14).
> 
> **Solution:** Apply the filter on the total number of documents rather than just the ones set by pagination

### CODE REVIEW

**Comment by SamZiemer** [comment]
ci:test:sf

**Comment by SamZiemer** [comment]
ci:test:stable

**Comment by joshuacords** [comment]
ci:test:search

**Comment by joshuacords** [comment]
At first glance I'm a bit concerned with the solution proposed. It appears to be adding an additional search to the call. Also, filtering all hits could lead to poor performance with high numbers of documents. I know we have a sliding window strategy parts of search that uses a configuration to set the accuracy, but the accuracy should be greater than 1 page. I'll need to see why that isn't being applied in this use case. 

I'll try to start my full review later today or tomorrow morning.

cc @amandaaakwok

**Comment by joshuacords** [comment]
Hello @amandaaakwok,

The issue you're trying to solve is actually handled by a configuration. See [LPS-78984](https://issues.liferay.com/browse/LPS-78984?focusedCommentId=1281695&page=com.atlassian.jira.plugin.system.issuetabpanels:comment-tabpanel#comment-1281695)

The customer should configure their **Permission Filtered Search Result Accurate Count Threshold** to whatever they feel is appropriate. Larger number are more taxing on the system, but are more accurate.

FYI, the Search Component is currently in the process of becoming a Unified Product Team (UPT). What that means for tickets is that LPPs/LPSs that are search related are the responsibility of the search team directly. Similar to forms tickets that should be given to the Brazil office, search tickets should be given to the search team. Currently that means they are assigned to me. I'll let you close out the LPP with the configuration information, and let me know if you have any questions.

**Comment by amandaaakwok** [comment]
Hi @joshuacords, 
Thanks for your input. I'll go ahead and relay this information on the LPP.

**Pull request closed without merging**
