### PR TITLE
journal-service: the head version of the JournalArticle will use the …

### PR DESCRIPTION
**Pull request by joshuacords**
…JournalArticleResource. This allows result rankings to always use the head version.

### CODE REVIEW

**Comment by joshuacords** [comment]
ci:test:sf

**Comment by joshuacords** [comment]
ci:test:search

**Comment by joshuacords** [comment]
Fixed the Similar results error. The Upgrade error will stay until later.

**Comment by joshuacords** [comment]
ci:test:sf

**Comment by joshuacords** [comment]
ci:test:search

**Comment by BryanEngler** [comment]
see https://github.com/joshuacords/liferay-portal/pull/114

**Pull request closed without merging**
