### PR TITLE
LPS-119020 Add defaultLanguageId to ddmFormDefinition

### PR DESCRIPTION
**Pull request by MaiPham135**

### CODE REVIEW

**Comment by MaiPham135** [comment]
ci:test:relevant

**Comment by MaiPham135** [comment]
ci:test:sf

**Comment by joshuacords** [comment]
ci:test:sf

**Comment by joshuacords** [comment]
ci:test:relevant

**Comment by joshuacords** [comment]
ci:test:relevant

**Comment by joshuacords** [comment]
Hello @MaiPham135,
This is the same change as the last PR, can you tell me what's changed?

**Comment by joshuacords** [comment]
I'm still able to reproduce LPS-115891 after this fix is applied. Also, from what I see, the default locale present when creating the last web content using the steps in LPS-119020 is Portuguese before applying the fix, but English after applying it. If I switch the locale to pt-BR before entering "test" I still get the error.

**Pull request closed without merging**
