### PR TITLE
LPS-86161 Change StaleObjectStateExceptions to print using JSONSerializer

### PR DESCRIPTION
**Pull request by ricky-pan**
Relevant tickets:
https://issues.liferay.com/browse/LPS-86161
https://issues.liferay.com/browse/LPP-31875

PR description here: https://issues.liferay.com/browse/LPS-86161?focusedCommentId=1616423&page=com.atlassian.jira.plugin.system.issuetabpanels:comment-tabpanel#comment-1616423

### CODE REVIEW

**Comment by ricky-pan** [comment]
ci:test:relevant

**Comment by joshuacords** [comment]
Discussed this with @ricky-pan - there should be these changes:

- Change _getAdmin to _setPermissionChecker and handle the exception that could be thrown there. (This also removes the code that returns a new exception instead of the old one)
- Don't use for-loop for getUser, see if you can just return the first admin user.
- Format Source

**Comment by joshuacords** [comment]
I'm expecting the changes soon so I'll leave this open.

**Comment by joshuacords** [comment]
Closing this PR - the fix was ultimately committed here: https://github.com/brianchandotcom/liferay-portal/pull/65053

**Pull request closed without merging**
